apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.secretName }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgres.auth.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.auth.password | quote }}
  POSTGRES_DB: {{ .Values.postgres.auth.database | quote }}
  DB_DSN: "user={{ .Values.postgres.auth.user }} password={{ .Values.postgres.auth.password }} host={{ .Values.postgres.dsnHost }} port=5432 dbname={{ .Values.postgres.auth.database }} sslmode=disable"
